Update README
AstuteSource/chasten pull request #123
Opened 2023-12-05 02:37 UTC by Jaclynpqc

The purpose of this pull request is to enhance the README file by organizing sections, providing a detailed comparison between Chasten and Symbex, suggesting similar tools, and offering a quick reference for Chasten command options. These changes aim to improve user understanding, facilitate tool selection, and enhance overall documentation.

**Changes Made:**

- Section Organization: Organized sections in the README file for better clarity and readability.

- Chasten vs. Symbex Comparison Section: Added a new section titled `🤓 Chasten vs. Symbex` to provide a detailed comparison between Chasten and Symbex. This section covers their command-line interfaces (CLI) and functionality, helping users make informed decisions based on their preferences and requirements.

- Similar Tools Section: Introduced a section titled `📦 Similar Tools` that highlights alternative tools for code analysis. Included brief descriptions of two tools: pyastgrep by Luke Plant and treesitter.

- chasten--help Section: Added a new section titled `✨chasten--help` to showcase the available options when using the chasten command. This provides users with quick reference information on how to interact with Chasten through the command line.

2023-12-05 14:59 UTC, AlishChhetri commented
This looks great, but I also have a few additions/ changes to the readme on a file I have not PRed yet. Would I be able to wrap that up and jump onto this PR, or should I just make another? I will have my edits in for review by the lab.

2023-12-05 15:17 UTC, AlishChhetri commented
@Jaclynpqc Its about adding a section dedicated to testing and additional details about setting up the developer environment. Most of the content will have a focus on providing more details for future developers of the tool.

2023-12-05 17:04 UTC, boulais01 approved these changes

2023-12-05 19:15 UTC, laurennevill commented
If its okay with @Jaclynpqc, lets have @AlishChhetri jump on and add his README changes so that we can get all changes pushed at once!

2023-12-08 14:11 UTC, laurennevill requested changes

2023-12-08 14:11 UTC, laurennevill commented on README.md
> +- The developement and use of Chasten requires [Python 3.11](https://www.python.org/downloads/release/python-3115/), must be greater or equal to version 3.11.5.
minor typo: development*

2023-12-08 20:27 UTC, laurennevill approved these changes

2023-12-08 20:27 UTC, AlishChhetri submitted a review, later dismissed
Looks great!

2023-12-08 20:46 UTC, merged