Add Dockerfile for developers to use to run Chasten
AstuteSource/chasten pull request #53
Opened 2023-09-15 13:28 UTC by AidanNeeson

Includes the addition of a Dockerfile that allows for developers to run Chasten without the fuss of OS specific dependency issues. Issue #40 includes the steps necessary to create the container, run, and manage it. A wiki would be helpful to document these steps so they will not clog up the README.

2023-09-15 13:38 UTC, jnormile approved these changes
Super useful for getting remaining members of the dev team up and running! Thanks for putting this together!

Alish is looking at integrating the information from the issue tracker about building/running the container into the chasten documentation that will be built by Quarto and hosted via GitHub Pages.

2023-09-19 17:42 UTC, gkapfham requested changes
Can you please include some documentation, perhaps in the README.md file, about how to use this Dockerfile? Without the specific command for using Docker with this specific Docker container, I'm concerned that this will not see significant use. Thanks! Finally, @AidanNeeson you are welcome to assign this issue to someone in our team.

2023-09-19 19:00 UTC, jnormile commented
The added content looks good to me--appreciate the different commands for multiple OSs being explicitly stated!

2023-09-26 19:21 UTC, laurennevill approved these changes
I believe this could be really helpful for those who are still struggling to get the project working on their machines. Great work

2023-09-26 19:45 UTC, Finley8 approved these changes
From personal experience of using DockerFile on my computer, this fully works and is very helpful.

2023-09-26 19:49 UTC, gkapfham commented
> From personal experience of using DockerFile on my computer, this fully works and is very helpful.

Hi @Finley8, thanks for confirming. Looking forward to future PR   reviews that you may complete, I suggest that you also furnish evidence that the command(s) worked by showing program output in your terminal window in the PR review. See what I mean? Overall, the more concrete output that we can provide the better we can establish a confidence in the correctness of the PR.

2023-09-26 19:53 UTC, gkapfham requested changes
Hi @AidanNeeson, thanks for preparing this `Dockerfile`!

I have suggested two small phrasing improvements. Can someone on the team make these small changes?

Also, we don't need to make this change now: but, maybe later at the top of the README file we should mention Docker?

2023-09-26 19:53 UTC, gkapfham commented on README.md
> +- Install Docker Desktop for your operating system
Should we provide a link to Docker Desktop? Maybe this link?

https://docs.docker.com/get-docker/

2023-09-26 19:53 UTC, gkapfham commented on README.md
> +There is also the option to use [Docker](https://www.docker.com/) to interact with `chasten`
Instead of the words "interact with", I suggest that we write "use". See what I mean?

2023-09-27 02:01 UTC, gkapfham approved these changes
Approved, thanks for making the requested changes.

2023-09-27 17:19 UTC, laurennevill approved these changes

2023-10-02 12:46 UTC, hayleepierce approved these changes

2023-10-02 22:54 UTC, merged